### PR TITLE
Upgrade dependencies to fix endpoints compatibility issue

### PR DESCRIPTION
**Pull request by cehoffman**
I upgraded to the latest controller-runtime which bumped all the other dependencies. I also took the opportunity to update the go version to 1.23. Tests pass locally for me and the created container from this fixes issue #22 for me.

### CODE REVIEW

**Review by Kristian-ZH — DISMISSED** [review]

**Comment by Kristian-ZH** [comment]
Thanks for the contributions
LGTM

**Comment by Kristian-ZH** [comment]
Can you please fix this one in order to make the CI pass:
```
/home/runner/work/endpoint-copier-operator/endpoint-copier-operator/go.mod:3: invalid go version '1.23.0': must match format 1.23
```

**Comment by cehoffman** [comment]
Made change. Interesting note it was the go toolchain itself that update the mod file version.

**Comment by cehoffman** [comment]
Updated the workflow.

**Comment by Kristian-ZH** [comment]
Thanks, LGTM!

**Review by Kristian-ZH — APPROVED** [review]

**Pull request merged**
